// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szwbhopysmrdyiwvjyhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6d2Job3B5c21yZHlpd3ZqeWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDQwNTcsImV4cCI6MjA3MTE4MDA1N30.pP3e0TzhVvBnriNhYQGq6i1g_loNn8UjBYJSi9M3Xh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});